import Head from "next/head";
import HomeModule from "@/modules/landing/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Кафедра ІТВС</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <HomeModule />
      </main>
    </>
  );
}
