import Head from "next/head";
import { Button } from "@/components/Button/Button";
import { useTheme } from "next-themes";
import { AuthShowcase } from "@/components/dashboard/Header/components/AuthShowcase";

export default function Home() {
  const { setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Кафедра ІТВС</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section>
          <Button variant="ghost" onClick={() => setTheme("light")}>
            Light
          </Button>
          <Button variant="ghost" onClick={() => setTheme("dark")}>
            Dark
          </Button>
          <Button variant="ghost" onClick={() => setTheme("system")}>
            System
          </Button>
        </section>
        <section>
          <AuthShowcase />
        </section>
      </main>
    </>
  );
}
